### PR TITLE
Add paper

### PR DESCRIPTION
**Pull request by Franck-Dernoncourt**

### CODE REVIEW

**Comment by Mihir3009** [comment]
Added it.

**Comment by Franck-Dernoncourt** [comment]
thanks @Mihir3009 can you also please add:

> ## Citation
> 
> If you use this work in your research, please cite our paper [Towards Enhancing Coherence in Extractive Summarization: Dataset and Experiments with LLMs](https://arxiv.org/pdf/2407.04855) as follows:
> 
> ```
> @misc{parmar2024enhancingcoherenceextractivesummarization,
>       title={Towards Enhancing Coherence in Extractive Summarization: Dataset and Experiments with LLMs}, 
>       author={Mihir Parmar and Hanieh Deilamsalehy and Franck Dernoncourt and Seunghyun Yoon and Ryan A. Rossi and Trung Bui},
>       year={2024},
>       eprint={2407.04855},
>       archivePrefix={arXiv},
>       primaryClass={cs.CL},
>       url={https://arxiv.org/abs/2407.04855}, 
> }
> ```
> 

before the license section?

thanks!

**Comment by Franck-Dernoncourt** [comment]
(or you can simply merge my PR)

**Comment by Mihir3009** [comment]
Done

**Pull request closed without merging**
